id: P004290
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:07:59.908117
source_metadata:
  id: bdr:W1KG20707
  title: རྫོགས་པ་ཆེན་པོ་ངལ་གསོ་སྐོར་གསུམ།
  author: ''
  volumes:
    da1af06d39c44786b62adc6efb08abd5:
      image_group_id: I1KG20779
      title: ''
      volume_number: 1
      total_pages: 1616
      base_file: v001.txt
    10fc43670716469bbabc6966d1eb8dd5:
      image_group_id: I1KG20780
      title: ''
      volume_number: 2
      total_pages: 1170
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
