id: I269B9696
legacy_id: P004290
ocr_import_info:
  bdrc_scan_id: W1KG20707
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T20:08:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T10:24:53.267369+00:00'
last_modified: 2022-08-31 18:27:46.882401
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG20707
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG20707
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་པ་ཆེན་པོ་ངལ་གསོ་སྐོར་གསུམ།
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.8550170861172702
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG20779:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG20779
      total_pages: 1616
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG20779.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8616661060502413
    legacy_id: v001
  I1KG20780:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG20780
      total_pages: 1170
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG20780.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.845353494711138
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
