id: I269B9696
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T20:15:39+00:00'
last_modified: '2022-06-07T21:43:41.740080+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG20707
  title: རྫོགས་པ་ཆེན་པོ་ངལ་གསོ་སྐོར་གསུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7BFB:
      image_group_id: I1KG20779
      title: ''
      total_pages: 1616
      order: 1
      base_file: 7BFB.txt
    DB00:
      image_group_id: I1KG20780
      title: ''
      total_pages: 1170
      order: 2
      base_file: DB00.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
